title: "Just for me"
logo: images/logo/logo.png
author: "QbQi (aloha@qbqi.dev)"
copyright: "2023"
email: aloha@qbqi.dev
description: >-
  아 이건 그냥 내가 보려고.

execute:
  execute_notebooks: cache
  allow_errors: true
  timeout: 120

html:
  favicon: images/logo/logo.ico
  home_page_in_navbar: false
  use_repository_button: true

repository:
  url: https://github.com/QbQi/Just-for-me
  branch: main
  path_to_book: docs
